run_id: "tiny_mean_reversion"
start_date: "2024-05-01"
end_date: "2025-05-01"

# === Logging ===
log_level: "DEBUG"  
log_to_console: true
log_to_file: true
structured_logging: true

# === Universe ===
universe_file: "universe/tiny_universe.csv"

# === Data ===
data:
  db_path: "db/ohlcv.duckdb"
  rolling: true
  window: 20
  cache_path: auto
  force_reload: false

# === Portfolio Value ===
initial_portfolio_value: 1000  # SINGLE SOURCE OF TRUTH - used for initial_equity and execution model

# === Alpha Model ===
alpha_model:
  name: "mean_reversion"
  params:
    threshold: 0.2
    features:
      - name: zscore_price
        params:
          period: 20
      - name: bollinger_band
        params:
          period: 20
          std_dev: 2.0

# === Risk Model ===
risk_model:
  name: "position_limit"
  params:
    max_leverage: 1.0
    max_position_size: 0.25
    allow_shorts: true

# === Transaction Cost Model ===
tx_cost_model:
  name: "quadratic_market_impact"
  params:
    commission_rate: 0.000001  
    impact_coefficient: 0.0000005 
    min_commission: 0.01  

# === Portfolio Construction Model ===
portfolio_model:
  name: "volatility_scaled"
  params:
    vol_lookback: 20
    risk_target: 0.5
    max_weight: 0.25
    min_notional: 1.0
    min_price: 1.0
    max_dollar_per_symbol: 500

# === Execution Model ===
execution_model:
  name: "market"
  params:
    slippage: 0.0001      
    commission: 0.0001
    # Remove initial_portfolio_value - will use the global one
    fractional: true
    allow_shorts: true
    min_notional: 5.0

# === Other Constraints ===
min_holding_period: 1
settlement_delay: 1
window: 20
rolling: true
